version: '3.9'

services:
  server:
    build: ./server
    ports:
      - 5000:5000
  db:
    image: postgres:14
    user: 'postgres'
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 4321:4321
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: 'pgdb'
      POSTGRES_HOST: localhost

volumes:
  database: